language: cpp

before_install:
  - sudo add-apt-repository ppa:fkrull/deadsnakes -y
  - sudo apt-get update -qq
  - pip install --user cpp-coveralls

install:
  - sudo apt-get install -y -qq zlib1g-dev python3.5

script:
  - make NO_APPSIGN=1
  - make PYTHON=python3.5 check
  - make clean
  - sudo apt-get install -y -qq libssl-dev libgmp-dev
  - make
  - make PYTHON=python3.5 check
  - make PYTHON=python3.5 coverage

after_success:
  - coveralls --gcov-options '\-lp'

notifications:
  irc:
    channels:
      - "irc.choopa.net#spasm-ng"
    on_success: change
    on_failure: always
    skip_join: true
